server_name: device-a4

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a4"
      password: "cdf19cfa9f798a7d6b3303fd"
      permissions: {
        publish: { allow: ["device.a4.outgoing.data"] }
        subscribe: { allow: ["device.a4.incoming.data"] }
      }
    }
  ]
}
