server_name: device-a3

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a3"
      password: "0f909f818238cc39aa0fc5e0"
      permissions: {
        publish: { allow: ["device.a3.outgoing.data"] }
        subscribe: { allow: ["device.a3.incoming.data"] }
      }
    }
  ]
}
