server_name: device-a2

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a2"
      password: "5cf51e1261959f1a0f1f87fe"
      permissions: {
        publish: { allow: ["device.a2.outgoing.data"] }
        subscribe: { allow: ["device.a2.incoming.data"] }
      }
    }
  ]
}
