server_name: device-a5

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a5"
      password: "34f49c3196c03146e5ea1f2b"
      permissions: {
        publish: { allow: ["device.a5.outgoing.data"] }
        subscribe: { allow: ["device.a5.incoming.data"] }
      }
    }
  ]
}
