server_name: device-a6

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a6"
      password: "850cd878b843c0a74fdcd9d6"
      permissions: {
        publish: { allow: ["device.a6.outgoing.data"] }
        subscribe: { allow: ["device.a6.incoming.data"] }
      }
    }
  ]
}
