server_name: device-a1

port: 4222
http_port: 8222

leafnodes {
  remotes = [
    { url: "leaf://nats-remote:7422", credentials: "/etc/nats/leaf.creds" }
  ]
}

authorization {
  users = [
    {
      user: "a1"
      password: "775a23e2d62b24ff4b13935e"
      permissions: {
        publish: { allow: ["device.a1.outgoing.data"] }
        subscribe: { allow: ["device.a1.incoming.data"] }
      }
    }
  ]
}
