services:
  nats-a3:
    image: nats:2.10-alpine
    container_name: nats-a3
    command: ["-c", "/etc/nats/device.conf"]
    volumes:
      - ./nats-config/device-a3.conf:/etc/nats/device.conf:ro
      - ./nsc-data/creds/a3.creds:/etc/nats/leaf.creds:ro
    networks:
      default: {}

  device-a3-client:
    build: ./app
    container_name: device-a3-client
    environment:
      ROLE: device
      DEVICE_ID: a3
      NATS_URL: nats://nats-a3:4222
      NATS_USER: a3
      NATS_PASS: 0f909f818238cc39aa0fc5e0
    depends_on:
      - nats-a3
    networks:
      default: {}

networks:
  default:
    name: multi-nats_default
    external: true
