services:
  nats-a5:
    image: nats:2.10-alpine
    container_name: nats-a5
    command: ["-c", "/etc/nats/device.conf"]
    volumes:
      - ./nats-config/device-a5.conf:/etc/nats/device.conf:ro
      - ./nsc-data/creds/a5.creds:/etc/nats/leaf.creds:ro
    networks:
      default: {}

  device-a5-client:
    build: ./app
    container_name: device-a5-client
    environment:
      ROLE: device
      DEVICE_ID: a5
      NATS_URL: nats://nats-a5:4222
      NATS_USER: a5
      NATS_PASS: 34f49c3196c03146e5ea1f2b
    depends_on:
      - nats-a5
    networks:
      default: {}

networks:
  default:
    name: multi-nats_default
    external: true
