services:
  nats-a1:
    image: nats:2.10-alpine
    container_name: nats-a1
    command: ["-c", "/etc/nats/device.conf"]
    volumes:
      - ./nats-config/device-a1.conf:/etc/nats/device.conf:ro
      - ./nsc-data/creds/a1.creds:/etc/nats/leaf.creds:ro
    networks:
      default: {}

  device-a1-client:
    build: ./app
    container_name: device-a1-client
    environment:
      ROLE: device
      DEVICE_ID: a1
      NATS_URL: nats://nats-a1:4222
      NATS_USER: a1
      NATS_PASS: 775a23e2d62b24ff4b13935e
    depends_on:
      - nats-a1
    networks:
      default: {}

networks:
  default:
    name: multi-nats_default
    external: true
