services:
  nats-a6:
    image: nats:2.10-alpine
    container_name: nats-a6
    command: ["-c", "/etc/nats/device.conf"]
    volumes:
      - ./nats-config/device-a6.conf:/etc/nats/device.conf:ro
      - ./nsc-data/creds/a6.creds:/etc/nats/leaf.creds:ro
    networks:
      default: {}

  device-a6-client:
    build: ./app
    container_name: device-a6-client
    environment:
      ROLE: device
      DEVICE_ID: a6
      NATS_URL: nats://nats-a6:4222
      NATS_USER: a6
      NATS_PASS: 850cd878b843c0a74fdcd9d6
    depends_on:
      - nats-a6
    networks:
      default: {}

networks:
  default:
    name: multi-nats_default
    external: true
