services:
  nats-a4:
    image: nats:2.10-alpine
    container_name: nats-a4
    command: ["-c", "/etc/nats/device.conf"]
    volumes:
      - ./nats-config/device-a4.conf:/etc/nats/device.conf:ro
      - ./nsc-data/creds/a4.creds:/etc/nats/leaf.creds:ro
    networks:
      default: {}

  device-a4-client:
    build: ./app
    container_name: device-a4-client
    environment:
      ROLE: device
      DEVICE_ID: a4
      NATS_URL: nats://nats-a4:4222
      NATS_USER: a4
      NATS_PASS: cdf19cfa9f798a7d6b3303fd
    depends_on:
      - nats-a4
    networks:
      default: {}

networks:
  default:
    name: multi-nats_default
    external: true
